version: "3.9"
services:
  bloggy-db:
    image: postgres
    restart: always
    container_name: bloggy-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /datadb/postgres
    volumes:
      - postgres:/datadb/postgres
volumes:
  postgres: